site_name: robolab-docs
theme:
  name: material
  logo: assets/icon-nao.svg
  favicon: assets/icon-nao.svg
  features:
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - navigation.top
    # - toc.integrate 
    - navigation.path
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang: en
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      title: On this page
  - def_list
  - pymdownx.tabbed:
      alternate_style: true

copyright: Documentation by Sean O'Connor at Bucknell University, 2023
extra:
  generator: false

nav:
    - Home: 'index.md'
    - Getting Started:
      - Installing Software: getting-started/installing-software.md
      - Using robolab-installer: getting-started/robolab-installer.md
      - Manual Installation: getting-started/manual-installation.md
    - NAOqi C++ SDK:
      - Creating your first C++ project: cpp-sdk/first-cpp-project.md
    - References: 'references.md'